export function openGoogleCalendar(
    futureTitle: string,
    timeline: { time: string; title: string }[]
) {
    const start = new Date()

    start.setHours(18, 0, 0, 0)

    const end = new Date(start)
    end.setHours(19)

    const format = (date: Date) =>
        date
            .toISOString()
            .replace(/[-:]/g, "")
            .split(".")[0] + "Z"

    const details = [
        `Future: ${futureTitle}`,
        "",
        "Execution Plan",
        "",
        ...timeline.map(item => `• ${item.time}: ${item.title}`),
        "",
        "Generated by Deadline Guardian",
    ].join("\n")

    const url =
        "https://calendar.google.com/calendar/render?action=TEMPLATE" +
        `&text=${encodeURIComponent(
            "Deadline Guardian Execution Plan"
        )}` +
        `&dates=${format(start)}/${format(end)}` +
        `&details=${encodeURIComponent(details)}`

    window.open(url, "_blank")
}